macroScript M4dsImportExport
category:"_MafiaTools"
buttonText:"4ds Imp/Exp"
toolTip:"4ds Import Export"
autoUndoEnabled:false 
(    
    on execute do (
        filein "ui_imp_exp.ms"	                
    )		
)

macroScript M4dsParamEditor
category:"_MafiaTools"
buttonText:"4ds PE"
toolTip:"4ds Parameter Editor"
autoUndoEnabled:false 
(    
    on execute do (
        filein "ui_param_editor.ms"	                
    )		
)